Convert type system flow to TypeScript
userdive/userdive.js pull request #42
Opened 2017-10-03 06:12 UTC by shkumagai

とりあえずTS化。
`yarn run test:karma` が `exit code 1` で終了する原因が分かってない。

2017-10-03 10:17 UTC, shkumagai commented on karma.conf.js
> +    mime: {
`mime` を指定したらテストが実行されるようになった

2017-10-03 10:20 UTC, shkumagai commented on webpack.config.ts
> +    path: path.join(__dirname, '/build/'),
`output` 先がこれで正しいかどうかはよく分かってない。

2017-10-04 00:44 UTC, 9renpoto commented
please rebase it.
and convert to `karma.conf.ts` 

refs: http://karma-runner.github.io/1.0/config/configuration-file.html

2017-10-04 02:14 UTC, 9renpoto commented on src/index.ts
> +export default function (name: any, source: any, global: any): Function {
`s/any/string | null` ?

2017-10-04 02:15 UTC, 9renpoto commented on tsconfig.json
> +    "noImplicitAny": false,
please set it as true if possible

2017-10-04 02:47 UTC, 9renpoto requested changes

2017-10-04 02:47 UTC, 9renpoto commented on tsconfig.json
> +    "noImplicitAny": false,
@shkumagai please `npImplicitAny` is activate

2017-10-04 12:01 UTC, 9renpoto reviewed
![LGTM](https://media.giphy.com/media/l2JJFL9d0TPFgS3v2/giphy.gif)

2017-10-04 12:01 UTC, 9renpoto approved these changes

2017-10-04 12:02 UTC, merged